---
- name: Common Tasks
  hosts: all
  become: yes
  gather_facts: true
  roles:
    - common

- name: Set Up Docker
  hosts: docker_hosts
  become: yes
  gather_facts: true
  roles:
    - docker
  tags:
    - docker

- name: Set Up Home Automation Containers
  hosts:
    - roland
  roles:
    - automation_host
  tags:
    - home_auto
