---
- name: Update Raspbian Hosts
  include_tasks: raspbian.yml
  when: "'raspberry_pis' in group_names"
  tags:
    - packaging

- name: Update CentOS Hosts
  include_tasks: centos.yml
  when: "'centos' in group_names"
  tags:
    - packaging

- name: Update /etc/hosts
  copy:
    src: etc_hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
    backup: yes
    decrypt: yes

- name: Install dotfiles
  copy:
    src: ../../../../dotfiles/
    dest: "/home/{{ ansible_ssh_user }}"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: Set Up Homebrew
  include_tasks: homebrew.yml
  when: install_homebrew
  tags:
    - homebrew

- name: Backup sshd config before updates
  copy:
    src: /etc/ssh/sshd_config
    remote_src: yes
    dest: /etc/ssh/sshd_config
    backup: yes

- name: Configure Login Banner
  include_tasks: banner.yml

- name: Configure Host MotD
  include_tasks: motd.yml

- name: Configure sshd
  include_tasks: ssh_config.yml
