- name: Update Repo Data
  apt:
    update_cache: yes
  tags:
    - packaging

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
  tags:
    - packaging

- name: Add universal additional packages
  apt:
    name: '{{ additional_packages }}'
    state: present
  tags:
    - packaging

- name: Add Debian-specific packages
  apt:
    name: '{{ debian_additional_packages }}'
    state: present
  tags:
    - packaging

- name: Make sure python3 is available as an alternative
  shell: update-alternatives --install /usr/bin/python python /usr/bin/python3 1
  tags:
    - python

- name: Set python3 as the system default
  shell: update-alternatives --set python /usr/bin/python3
  tags:
    - python
